### ISSUE TITLE
Install R Packages

### ISSUE THREAD

**Issue by jimhshen** [labordynamicsinstitute/idea-handbook#8]
How to configure travis.yml to get ggplot2 (and any other packges we might need in the future) to install?

Resources I've looked at so far without success:

https://stackoverflow.com/questions/45289764/install-r-packages-using-docker-file
http://jtleek.com/protocols/travis_bioc_devel/#Installing_required_packages
https://blog.rstudio.com/2016/03/09/r-on-travis-ci/
https://bookdown.org/yihui/bookdown/github.html
https://docs.travis-ci.com/user/languages/r/

**Comment by larsvilhuber** [comment]
See _setup.R, which is called by index.Rmd
